
title:   '芯芯向荣'
author:
  name:  'YingH'

production_url : http://wkongzhu.github.io

########
# more settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids:      true
  auto_id_prefix: 'id-'
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    line_numbers: true  
  
sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false

